# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usbhid" "sd_mod" "sdhci_pci" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9b21328e-e925-4bd9-9cb0-c37d4cb5bb32";
      fsType = "btrfs";
      options = [ "subvol=nixos" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/9b21328e-e925-4bd9-9cb0-c37d4cb5bb32";
      fsType = "btrfs";
      options = [ "subvol=nixos/var" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/9b21328e-e925-4bd9-9cb0-c37d4cb5bb32";
      fsType = "btrfs";
      options = [ "subvol=nixos/tmp" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/mnt/data" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "default" "noatime" "space_cache" "autodefrag" ];
    };

  boot.initrd.luks.devices."cr2-data".device = "/dev/disk/by-uuid/75236c0e-cad4-43a7-986c-a5f82f68cf65";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/dc12fafa-47e3-4f7c-a6a4-f3c14e06b4ff";
      fsType = "ext4";
      options = [ "default" "noatime" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fe64ceec-6658-4c46-abbd-23dd9a623814";
      fsType = "btrfs";
      options = [ "default" "noatime" "space_cache" "autodefrag" ];
    };

  boot.initrd.luks.devices."cr1-home".device = "/dev/disk/by-uuid/0184c496-d27d-4c70-88f6-d0b7aaed1e17";

  fileSystems."/home/mdo/.cache" =
    { device = "/dev/disk/by-uuid/fe64ceec-6658-4c46-abbd-23dd9a623814";
      fsType = "btrfs";
      options = [ "subvol=mdo/.cache" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/.m2" =
    { device = "/dev/disk/by-uuid/fe64ceec-6658-4c46-abbd-23dd9a623814";
      fsType = "btrfs";
      options = [ "subvol=mdo/.m2" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/.mozilla" =
    { device = "/dev/disk/by-uuid/fe64ceec-6658-4c46-abbd-23dd9a623814";
      fsType = "btrfs";
      options = [ "subvol=mdo/.mozilla" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/.thunderbird" =
    { device = "/dev/disk/by-uuid/fe64ceec-6658-4c46-abbd-23dd9a623814";
      fsType = "btrfs";
      options = [ "subvol=mdo/.thunderbird" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/OLD/.config" =
    { device = "/dev/disk/by-uuid/fe64ceec-6658-4c46-abbd-23dd9a623814";
      fsType = "btrfs";
      options = [ "subvol=mdo/.config" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/Music" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "subvol=music" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/Pictures" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "subvol=pictures" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/ISO" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "subvol=iso" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/android" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "subvol=android" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/Backups" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "subvol=backups" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/Videos" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "subvol=videos" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/src" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "subvol=src" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/Media" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "subvol=media" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/home/mdo/Downloads" =
    { device = "/dev/disk/by-uuid/527773ff-0f65-4132-bd4a-4dbc623f2c7d";
      fsType = "btrfs";
      options = [ "subvol=downloads" "default" "noatime" "space_cache" "autodefrag" ];
    };

  fileSystems."/var/lib/docker/btrfs" =
    { device = "/tmp/nixos/var/lib/docker/btrfs";
      fsType = "none";
      options = [ "bind" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/99be5bc9-fac4-4386-83c0-63632edef9dc"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
